apiVersion: v1
kind: Service
metadata:
  name: {{ include "globex-web.name" . }}
  labels:
    {{- include "globex-web.labels" . | nindent 4 }}
  annotations:
    {{- include "globex-web.argocd-syncwave" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "globex-web.selectorLabels" . | nindent 4 }}
