kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-argocd-dex-server
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-argocd-dex-server
    {{- if .Values.namespace }}
    namespace: {{ .Values.namespace }}
    {{- else }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-argocd-dex-server
