{{- if .Values.authentication -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authentication.clientId }}-client-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-broker.argocd-syncwave" . | nindent 4 }}
stringData:
  bootstrapServer: {{ include "kafka-broker.bootstrapServer" . }}
  securityProtocol: {{ .Values.authentication.securityProtocol }}
  saslMechanism: {{ .Values.authentication.saslMechanism }}
  clientId: {{ .Values.authentication.clientId }}
  clientSecret: {{ .Values.authentication.clientSecret }}
  {{- if eq .Values.authentication.saslMechanism "PLAIN" }}
  saslJaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ .Values.authentication.clientId }}" password="{{ .Values.authentication.clientSecret }}";
  {{- end }}
  {{- if eq .Values.authentication.saslMechanism "SCRAM-SHA-512" }}
  saslJaasConfig: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ .Values.authentication.clientId }}" password="{{ .Values.authentication.clientSecret }}";
  {{- end }}
type: Opaque
{{- end }}
