{{- if .Values.route.enabled -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "activity-tracking.name" . }}
  labels:
    {{- include "activity-tracking.labels" . | nindent 4 }}
  annotations:
    {{- include "activity-tracking.argocd-syncwave" . | nindent 4 }}
spec:
  {{ if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{ end }}
  to:
    kind: Service
    name: {{ include "activity-tracking.name" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.portName }}
  wildcardPolicy: None
  {{- if .Values.route.tlsEnabled }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{ end }}
{{ end }}