{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "activity-tracking.serviceAccountName" . }}
  labels:
    {{- include "activity-tracking.labels" . | nindent 4 }}
  annotations:
    {{- include "activity-tracking.argocd-syncwave" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
