{{- range untilStep 0 (.Values.loop.count | int64 | int) 1 }}
{{- $loop := printf "%s%s" $.Values.loop.prefix ((add . 1) | toString) }}
{{- range $item := $.Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ $loop }}-admin-{{ $item.name }}-{{ $loop }}-namespace'
  namespace: '{{ $item.name }}-{{ $loop }}'
subjects:
- kind: User
  name: '{{ $loop }}'
  namespace: '{{ $item.name }}-{{ $loop }}'
roleRef:
  kind: ClusterRole
  name: 'admin'
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}